env:
  - REPO="krishnan-mani/asb"
  - MY_CODEBASE="web"
  - CI_HOME=`pwd`/$REPO/$MY_CODEBASE
  - NODE_ENV=travis
language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install
script: grunt test
