env:
  - REPO="krishnan-mani/asb"
  - CI_HOME=`pwd`/$REPO
  - NODE_ENV=travis
language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
script: grunt test
